// Hotel Profile
export const FOOD_CLEAR = "FOOD_CLEAR";
export const FACILITIES_CLEAR = "FACILITIES_CLEAR";
export const ACTIVITIES_CLEAR = "ACTIVITIES_CLEAR";
export const CLEANING_CLEAR = "CLEANING_CLEAR";
export const GENERAL_CLEAR = "GENERAL_CLEAR";
export const HOUSERULES_CLEAR = "HOUSERULES_CLEAR";
export const SET_HOTELPROFILE = "SET_HOTELPROFILE";
export const SET_HOTELProfileImages = "SET_HOTELProfileImages";
export const ADD_HOTELPROFILE = "ADD_HOTELPROFILE";

// Room
export const SET_ROOM = "SET_ROOM";
export const ADD_ROOM = "ADD_ROOM";
export const SET_ROOMRESERVE = "SET_ROOMRESERVE";

// Auth Rep
export const SET_AUTHREP = "SET_AUTHREP";
export const SIGNUP_REP = "SIGNUP_REP";
export const SIGN_REP = "SIGNIN_REP";
export const SET_AUTHSUCCESS = "SET_AUTHSUCCESS";
export const LOAD_USER = "LOAD_USER";

// Auth Client
export const SET_AUTHCLIENT = "SET_AUTHCLIENT";
export const SET_AUTHCLIENTSUCCESS = "SET_AUTHCLIENTSUCCESS";
export const CLEAR_AUTHCLIENT = "CLEAR_AUTHCLIENT";

// View Hotels
export const VIEW_HOTELS = "VIEW_HOTELS";
export const UNIQUE_ROOMS = "UNIQUE_ROOMS";
export const UNIQUE_ROOMSHOTEL = "UNIQUE_ROOMSHOTEL";
export const HOTEL_DETAIL = "HOTEL_DETAIL";
export const SET_UNIQUEROOM = "SET_UNIQUEROOM";

// Guide Profile
export const SET_GUIDEPROFILE = "SET_GUIDEPROFILE";
export const REMOVE_PLACENAME = "REMOVE_PLACENAME";
export const ADD_GUIDEPROFILE = "ADD_GUIDEPROFILE";
export const GET_GUIDEDETAILS = "GET_GUIDEDETAILS";
export const SET_GUIDEITEMPROFILE = "SET_GUIDEITEMPROFILE";
// Payment
export const SET_PAYMENT = "SET_PAYMENT";
